from copy import deepcopy as dc
import numpy as np
import pandas as pd
from sklearn.preprocessing import StandardScaler, LabelEncoder
from statsmodels.tsa.stattools import adfuller

def apply_scale_to_categorical_features(df, categorical_features):
    ''' Applying feature scaling to categorical features '''

    label_encoder = LabelEncoder()
    scaled_categorical_values = label_encoder.fit_transform(df[categorical_features].values.ravel())
    scaled_categorical_df = pd.DataFrame(scaled_categorical_values, columns=categorical_features, index=df.index)
    #display(scaled_categorical_df)

    return scaled_categorical_df

def apply_scale_to_numerical_features(df, numerical_features):
    ''' Applying feature scaling to numerical features '''

    # scaler = MinMaxScaler(feature_range=(0, 1)) # Initialize MinMaxScaler
    scaler = StandardScaler()
    scaled_numerical_values = scaler.fit_transform(df[numerical_features])
    # Create a DataFrame with the scaled numerical values
    scaled_numerical_df = pd.DataFrame(scaled_numerical_values, columns=numerical_features, index=df.index)
    #display(scaled_numerical_df)

    return scaler, scaled_numerical_df

def generate_lag_features(df, feature_columns, target_columns, window):
    '''     Create lag features     '''

    X = []  # input sequences
    y = []  # target values
    time_sequences_df = dc(df)   # Deep copy the dataframe to avoid modifying the original data
    #display(time_sequences_df)

    # Create time-shifted features
    for col in time_sequences_df.columns:
        #print("column: ", col)
        for i in range(1, window + 1):
            time_sequences_df[f'{col}(t-{i})'] = time_sequences_df[col].shift(i)

    # Drop rows with NaN values generated by the shift
    time_sequences_df.dropna(inplace=True)

    # Extract input sequences and target values
    #print("feature_columns: ", feature_columns)
    #print("target_columns: ", target_columns)
    for _, row in time_sequences_df.iterrows():
        sequence = []
        for i in range(window, 0, -1):
            sequence.append([row[f'{col}(t-{i})'] for col in feature_columns])
        X.append(sequence)
        y.append([row[target.capitalize()] for target in target_columns])

    return time_sequences_df, np.array(X), np.array(y)

def apply_denormalization(scaler, predictions, actuals):
    # Convert to numpy arrays for easier manipulation
    predictions = np.array(predictions)
    actuals = np.array(actuals)

    # Denormalize the predictions and actuals
    predictions_denorm = scaler.inverse_transform(predictions)
    actuals_denorm = scaler.inverse_transform(actuals)

    return predictions_denorm, actuals_denorm


def check_stationarity(timeseries):
    ''' Check if time series is stationary  '''
    isStationary = True

    # Perform the ADF test
    adf_result = adfuller(timeseries)
    adf_statistic = adf_result[0]
    p_value = adf_result[1]

    if p_value > 0.05:
        isStationary = False

    return adf_statistic, p_value, isStationary

# Reverse the smoothing level for forecasted and test values
def reverse_smoothing(df, trends_dict, forecast_steps):
    df_without_smooth = df.copy()
    for col in df.columns:
        # Only reverse smoothing for non-stationary series
        if col in trends_dict and trends_dict[col].notna().all():
            trend_length = len(trends_dict[col])
            if trend_length >= forecast_steps:
                # Add back the trend for the forecasted steps
                df_without_smooth[col] += trends_dict[col][-forecast_steps:].values
            else:
                print(f"Warning: Trend length for {col} is shorter than forecast steps")
        else:
            #print(f"No trend found for column: {col}")
            print("")
    
    return df_without_smooth

# Reverse the log transformation
def reverse_log(df):
    return np.expm1(df)  # Assuming the original data was transformed using log1p